// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardProduct: typeof import('./src/components/Card/CardProduct.vue')['default']
    CartModal: typeof import('./src/components/Modal/CartModal.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Modal: typeof import('./src/components/Modal/Modal.vue')['default']
    Navbar: typeof import('./src/components/Navbar/Navbar.vue')['default']
    ProductOverview: typeof import('./src/components/Product/ProductOverview.vue')['default']
    ProductSummary: typeof import('./src/components/Product/ProductSummary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
